version: '3.7'
services:
  server:
    container_name: server
    hostname: nodejs
    restart: always
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - dev
    depends_on:
      - mariadb
      - rabbitmq
    links:
      - "mariadb:mariadb.db"
      - "rabbitmq:rabbitmq"
  mariadb:
    hostname: mariadb
    image: mariadb
    restart: always
    ports:
      - "3333:3306"
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    env_file:
      - ./.env
    networks:
      - dev
    volumes:
      - mariadb:/var/lib/mysql
    logging:
      driver: none
  rabbitmq:
    image: "rabbitmq:3"
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - '5672:5672'
    networks:
      - dev
    logging:
      driver: none
networks:
  dev:
volumes:
  mariadb:
  rabbitmq:
